export const FETCH_BUTTON_CLICKED = 'FETCH_BUTTON_CLICKED';
export const PLANETS_RECEIVED = 'PLANETS_RECEIVED';
export const PLANET_CLICKED = 'PLANET_CLICKED';
export const RESIDENTS_RECEIVED = 'RESIDENTS_RECEIVED';
export const SWAPI_URL = 'https://swapi.co/api/';